name: "Setup UV"
description: "Install UV, set up Python, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Install UV
      uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        enable-cache: true
        python-version: ${{ env.PYTHON }}

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-groups
