name: CI Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  code-change:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      code: ${{ steps.filter.outputs.code }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - '.github/actions/**'
              - '.github/workflows/**'
              - 'rekordbox_edit/**'
              - 'tests/**'
              - 'pyproject.toml'
              - 'uv.lock'
              - 'Makefile'
              - 'ruff.toml'

  lint:
    name: 🧺 Lint
    runs-on: ubuntu-latest
    if: ${{ needs.code-change.outputs.code == 'true' }}
    env:
      PYTHON: "3.13"
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run lint tests
        uses: ./.github/actions/lint

  unit-tests:
    name: 🧪 Tests
    needs: code-change
    if: ${{ needs.code-change.outputs.should_skip != 'true' && needs.code-change.outputs.code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.14"] # oldest and latest
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run unit tests
        uses: ./.github/actions/test
  all-green:
    name: ✅ All Green
    if: always()
    needs:
      - lint
      - unit-tests
    runs-on: Ubuntu-latest

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: unit-tests, lint
          jobs: ${{ toJSON(needs) }}
